url: https://www.skynettoday.com
baseurl: 

name: Skynet Today
title: Skynet Today
description: Putting AI News In Perspective
logo: /assets/img/logo.png
imgpath: /assets/img
locale: en_us
lang: en
google_analytics: UA-114440651-1

feed:
  path: feed.xml

  # Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image:
        feature: assets/img/placeholder.png
      comments: true
      share: true
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
    values:
      layout: page

permalink: /:categories/:title/

plugins: 
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-last-modified-at
    - jekyll-gist
    - jekyll-redirect-from 
    - jekyll-feed 

markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  enable_coderay: false

include: [".htaccess","_pages"]
exclude: ["CNAME", "_deploy.yml", "lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor", "scripts"]

# Read Time
read_time: false # set true if you want read time under headline
words_per_minute: 250

# Category Colors
briefs: 0c776d
editorials: 940b52
digests: 103558

# Social
footer_links:
  - title: Feed
    url: feed.xml
    icon: assets/img/icons/rss.svg
  - title: Twitter
    url: https://twitter.com/skynet_today
    icon: assets/img/icons/twitter.svg
  - title: Facebook
    url: https://www.facebook.com/pg/TheSkynetToday/
    icon: assets/img/icons/facebook.svg

# Owner
owner:
  name: Andrey Kurenkov
  avatar: andrey_face.jpg
  email: andreyk@stanford.com
  web: //www.andreykurenkov.com
  disqus-shortname: skynet-today
  twitter: skynet_today

# Paginate
paginate: 40
